### ISSUE TITLE
Add Clone VehicleEntry function

### ISSUE THREAD

**Issue by derneuere** [burninrubber0/Bundle-Manager#4]
As a modder, I want a useful starting point when adding a vehicle. To do that, I would want to choose an entry, which I want to clone. This would improve the workflow as I would only need to change a couple of fields to add a new vehicle.

**Comment by burninrubber0** [comment]
Implemented in [v0.1.1](https://github.com/burninrubber0/Bundle-Manager/releases/tag/v0.1.1).
